## Transformation

In [1]:

import pandas as pd

In [432]:
df = pd.read_csv('./1Food_Inspections.csv')

In [435]:

#import os
#from src.etl import etl


#def load_ingestion(path):
#    return etl.load_df(path)

def estandariza_variables(df):
    columnas_antes=df.columns
    df.columns=df.columns.str.replace(' ','_')
    df.columns=df.columns.str.replace('#','num')
    df.columns=df.columns.str.lower()

#titanic.rename(columns={col: col.lower() for col in titanic.columns.values}, 
#        inplace=True)

def cambiar_minusculas_variable(archivo,variable):
    archivo[variable]=archivo[variable].str.lower()
    
    

def date_transformation(col,df):
    df[col]=pd.to_datetime(df[col])
    return df

def numeric_transformation(col,df):
    df[col]=pd.to_numeric(df[col], )
    return df

def categoric_trasformation(col,df):
    df = df.astype({col:'category'}) 
    return df

def time_transformation(col,df):
    df[col]=pd.to_datetime(df[col], errors='coerce',format='%H:%M:%S')
    return df

def data_imputation_state(col,df):
    return df[df[col]== "il"]

#def data_imputation_city(col,df):
#    return df[df[col]].replace(to_replace = ["312chicago", "cchicago", "chchicago", "chcicago", \
#                                            "chicagochicago", "chicagohicago", "chicagoi"], value= "chicago")

def data_imputation_spell(df):
    return df.replace(to_replace = ["312chicago", "cchicago", "chchicago", "chcicago", \
                                            "chicagochicago", "chicagohicago", "chicagoi", \
                                    "chicago."], value= "chicago")


def data_imputation_city(col,df):
    return df[df[col]== "chicago"]

#def save_transformation(df):
#    path = 'output/transformation_df.pkl'
#    utils.save_df(df, path)


def transform(df):
#def transform(path):
    #df = load_ingestion(path)
    estandariza_variables(df)
    
    
    categoric_trasformation('risk',df)   
    date_transformation('inspection_date',df)
    data_imputation_state('state',df)
    data_imputation_spell(df)
    data_imputation_city('city',df)
    
    return df
    
    #df['inspection_id']=df['inspection_id'].astype('str')
    #df['license_num']=df['license_num'].astype('str')
    #df['zip']=df['zip'].astype('str')
    
    #df = time_transformation('inspection_date',df)
    


    #save_transformation(df)

In [436]:
transform(df)

,inspection_id,dba_name,aka_name,license_num,facility_type,risk,address,city,state,zip,inspection_date,inspection_type,results,violations,latitude,longitude,location
0,2453552,CLAMP DOWN BURGERS,NaN,2749943.0,NaN,Risk 2 (Medium),1742 W DIVISION ST,CHICAGO,IL,60622.0,2020-10-20,License,No Entry,NaN,41.903387,-87.671740,"(-87.67174026586648, 41.903386755553484)"
1,2386633,JIN JU,JIN JU,27137.0,Restaurant,Risk 1 (High),5203 N CLARK ST,CHICAGO,IL,60640.0,2020-08-28,Canvass,No Entry,NaN,41.976301,-87.668276,"(-87.66827593789948, 41.97630115368914)"
2,2386595,LA BIZNAGA #2,LA BIZNAGA #2,2708992.0,NaN,Risk 1 (High),2949 W BELMONT AVE,CHICAGO,IL,60618.0,2020-08-27,Complaint,No Entry,NaN,41.939256,-87.702270,"(-87.70226967930802, 41.939255926667535)"
3,2386464,Uni Sushi Bristo,Uni Sushi Bistro,2262637.0,Restaurant,Risk 1 (High),1752 W NORTH AVE,CHICAGO,IL,60622.0,2020-08-25,Complaint,No Entry,NaN,41.910676,-87.672205,"(-87.67220465807979, 41.91067561170382)"
4,2386398,KIKI'S BISTRO,KIKI'S BISTRO,22899.0,Restaurant,Risk 1 (High),900 N FRANKLIN ST,CHICAGO,IL,60610.0,2020-08-24,Canvass,No Entry,NaN,41.898998,-87.635921,"(-87.63592067312285, 41.89899799424835)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215062,229233,"ZULLO'S MARKETS, LLC",ZULLO'S MARKET,2016915.0,Restaurant,Risk 2 (Medium),131 N Clinton ST,CHICAGO,IL,60661.0,2010-02-18,License,Fail,NaN,41.884188,-87.641120,"(-87.64111966683218, 41.884187507127805)"
215063,68205,LA FONDA CHIQUITA TLC,LA FONDA CHIQUITA,2017215.0,Restaurant,Risk 1 (High),5940 W DIVERSEY AVE,CHICAGO,IL,60639.0,2010-02-09,License,Fail,12. HAND WASHING FACILITIES: WITH SOAP AND SAN...,41.931260,-87.775203,"(-87.77520287598688, 41.93125971874477)"
215064,88234,KABAB CUISINE 2,KABAB CUISINE 2,2014076.0,Restaurant,Risk 1 (High),6320 N LINCOLN AVE,CHICAGO,IL,60659.0,2010-02-01,License Re-Inspection,Pass,NaN,41.996139,-87.716968,"(-87.71696834498202, 41.996139331170895)"
215065,74311,MARGARITA DISTRIBUTORS,NaN,2017298.0,Wholesale,Risk 3 (Low),2332 S BLUE ISLAND AVE BLDG,CHICAGO,IL,60608.0,2010-02-19,License Re-Inspection,Pass,NaN,41.849940,-87.672421,"(-87.67242100722251, 41.84994008002549)"
215066,67838,OUR LADY OF LOURDES,OUR LADY OF LOURDES,42577.0,Daycare (Under 2 Years),Risk 1 (High),1449 S KEELER AVE,CHICAGO,IL,60623.0,2010-01-12,Canvass,Fail,18. NO EVIDENCE OF RODENT OR INSECT OUTER OPEN...,41.861003,-87.729762,"(-87.72976247742804, 41.861003270876026)"

## Feature engineering

In [437]:

#import numpy as np
import pandas as pd
from datetime import datetime
from datetime import date
import string
#from src.utils import utils
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
#from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
#from sklearn.ensemble import RandomForestClassifier
#from sklearn.model_selection import TimeSeriesSplit
#from sklearn.model_selection import GridSearchCV


from sklearn.feature_selection import VarianceThreshold

In [438]:
def add_column_days(df):
    hoy = date.today().strftime("%Y-%m-%d")
    ins = df['inspection_date'].apply(lambda x: x.strftime("%Y-%m-%d"))
    fecha1 = datetime.strptime(hoy, "%Y-%m-%d")
    fecha2 = ins.apply(lambda x: datetime.strptime(x, "%Y-%m-%d"))
    df['days'] = fecha1 - fecha2
    return df

def add_column_month(df):
    df['inspection_month'] = df['inspection_date'].dt.month
    return df

def add_column_day(df):
    df['inspection_day'] = df['inspection_date'].dt.dayofweek
    return df

def add_column_violation_num(df):
    df['violations']=df['violations'].fillna("0")
    df['violation_num'] = df['violations'].apply(lambda row:[int(Numero) for Numero in row.split(".")\
                                                             if Numero.isdigit()][0])    
    return df



def add_column_pass(df):
    
    #df['results_des'] = df['results']

    dic_results = {'pass': 'pass',
                   'out of business': 'fail',
                   'no entry': 'fail',
                   'fail': 'fail',
                   'not ready': 'fail',
                   'pass w/ conditions': 'pass',
                   'business not located': 'fail'}
    df['pass'] = df.results.map(dic_results)
    return df


def add_column_risky(df):
    dic_risk = {'risk 1 (high)': 'high',
                   'risk 2 (medium)': 'medium',
                   'risk 3 (low)': 'low',
                   'all': 'high'}
    df['risky'] = df.risk.map(dic_risk)
    
    return df


def new_features(df):
    add_column_days(df)
    add_column_month(df)
    add_column_day(df)
    add_column_violation_num(df)
    add_column_pass(df)
    add_column_risky(df)
    return df


def feature_generation(df):
    df.inputs = df.drop(['aka_name', 'address', 'city', 'state','latitude', 'longitude', \
                         'location'], axis=1)
    return df.inputs

def feature_selection(df):
        #Dividir la base en train y test
    df_train,df_test = train_test_split(df,test_size=0.2,random_state=4,shuffle=True)

In [439]:
new_features(df)

useful_cols = ["Open", "High", "Low", "Close", "Volume"]
X = df_train.loc[:, useful_cols].values

,inspection_id,dba_name,aka_name,license_num,facility_type,risk,address,city,state,zip,...,violations,latitude,longitude,location,days,inspection_month,inspection_day,violation_num,pass,risky
0,2453552,CLAMP DOWN BURGERS,NaN,2749943.0,NaN,Risk 2 (Medium),1742 W DIVISION ST,CHICAGO,IL,60622.0,...,0,41.903387,-87.671740,"(-87.67174026586648, 41.903386755553484)",165 days,10,1,0,NaN,NaN
1,2386633,JIN JU,JIN JU,27137.0,Restaurant,Risk 1 (High),5203 N CLARK ST,CHICAGO,IL,60640.0,...,0,41.976301,-87.668276,"(-87.66827593789948, 41.97630115368914)",218 days,8,4,0,NaN,NaN
2,2386595,LA BIZNAGA #2,LA BIZNAGA #2,2708992.0,NaN,Risk 1 (High),2949 W BELMONT AVE,CHICAGO,IL,60618.0,...,0,41.939256,-87.702270,"(-87.70226967930802, 41.939255926667535)",219 days,8,3,0,NaN,NaN
3,2386464,Uni Sushi Bristo,Uni Sushi Bistro,2262637.0,Restaurant,Risk 1 (High),1752 W NORTH AVE,CHICAGO,IL,60622.0,...,0,41.910676,-87.672205,"(-87.67220465807979, 41.91067561170382)",221 days,8,1,0,NaN,NaN
4,2386398,KIKI'S BISTRO,KIKI'S BISTRO,22899.0,Restaurant,Risk 1 (High),900 N FRANKLIN ST,CHICAGO,IL,60610.0,...,0,41.898998,-87.635921,"(-87.63592067312285, 41.89899799424835)",222 days,8,0,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215062,229233,"ZULLO'S MARKETS, LLC",ZULLO'S MARKET,2016915.0,Restaurant,Risk 2 (Medium),131 N Clinton ST,CHICAGO,IL,60661.0,...,0,41.884188,-87.641120,"(-87.64111966683218, 41.884187507127805)",4062 days,2,3,0,NaN,NaN
215063,68205,LA FONDA CHIQUITA TLC,LA FONDA CHIQUITA,2017215.0,Restaurant,Risk 1 (High),5940 W DIVERSEY AVE,CHICAGO,IL,60639.0,...,12. HAND WASHING FACILITIES: WITH SOAP AND SAN...,41.931260,-87.775203,"(-87.77520287598688, 41.93125971874477)",4071 days,2,1,12,NaN,NaN
215064,88234,KABAB CUISINE 2,KABAB CUISINE 2,2014076.0,Restaurant,Risk 1 (High),6320 N LINCOLN AVE,CHICAGO,IL,60659.0,...,0,41.996139,-87.716968,"(-87.71696834498202, 41.996139331170895)",4079 days,2,0,0,NaN,NaN
215065,74311,MARGARITA DISTRIBUTORS,NaN,2017298.0,Wholesale,Risk 3 (Low),2332 S BLUE ISLAND AVE BLDG,CHICAGO,IL,60608.0,...,0,41.849940,-87.672421,"(-87.67242100722251, 41.84994008002549)",4061 days,2,4,0,NaN,NaN
215066,67838,OUR LADY OF LOURDES,OUR LADY OF LOURDES,42577.0,Daycare (Under 2 Years),Risk 1 (High),1449 S KEELER AVE,CHICAGO,IL,60623.0,...,18. NO EVIDENCE OF RODENT OR INSECT OUTER OPEN...,41.861003,-87.729762,"(-87.72976247742804, 41.861003270876026)",4099 days,1,1,18,NaN,NaN

In [440]:
def transform_newf(df):
    #categoric_trasformation('zip',df)
    #categoric_trasformation('inspection_type',df)
    categoric_trasformation('inspection_month',df)
    categoric_trasformation('inspection_day',df)
    categoric_trasformation('pass',df)
    categoric_trasformation('risky',df)

    #zip
#inspection_type
#results
#inspection_month
#inspection_day
#violations
#inspection_month
#inspection_day
transform_newf(df)

In [442]:
#class_encoder = OneHotEncoder(categories="auto")
#class_encoder.categories_
data_input = df.drop(['aka_name', 'risk', 'address', 'city', 'state','results', 'violations',\
                     'latitude', 'longitude', 'location'], axis=1)

transformers_2 = [('one_hot', OneHotEncoder(), ['inspection_month',\
                                               'inspection_day', 'pass', 'risky'])]



col_trans_2 = ColumnTransformer(transformers_2, remainder="drop", n_jobs=-1, verbose=True)


col_trans_2.fit(data_input)
df_input_vars = col_trans_2.transform(data_input)

KeyboardInterrupt:

In [ ]:
variance_threshold = VarianceThreshold(threshold=0.1)
variance_threshold.fit(df_input_vars)
variance_threshold.transform(df_input_vars)
variance_threshold.variances_
#data_input.columns

In [414]:

#df.inspection_type.unique()
#dfy = df.groupby('risky').nunique()
#dfy

#dfy[dfy['inspection_id']<100]

#sum(df['risk'].isnull())
#df[df['risk'] == 'all']
df.inputs.dtypes

inspection_id                 int64
dba_name                     object
license_num                 float64
facility_type                object
zip                         float64
inspection_date      datetime64[ns]
inspection_type              object
days                timedelta64[ns]
inspection_month              int64
inspection_day                int64
violation_num                 int64
pass                         object
risky                        object
dtype: object

In [69]:
feature_generation(df)
#imputar na:
#facility_type most_frequent
#risk most_frequent
#zip most_frequent
#inspection_type most_frequent

#one hot:
##facility_type
#risk
#zip
#inspection_type
#results
#inspection_month
#inspection_day
#violations
#inspection_month
#inspection_day

,inspection_id,dba_name,license_num,facility_type,risk,zip,inspection_date,inspection_type,results,violations,days,inspection_month,inspection_day
0,2453552,clamp down burgers,2749943.0,NaN,risk 2 (medium),60622.0,2020-10-20,license,no entry,NaN,164 days,10,20
1,2386633,jin ju,27137.0,restaurant,risk 1 (high),60640.0,2020-08-28,canvass,no entry,NaN,217 days,8,28
2,2386595,la biznaga #2,2708992.0,NaN,risk 1 (high),60618.0,2020-08-27,complaint,no entry,NaN,218 days,8,27
3,2386464,uni sushi bristo,2262637.0,restaurant,risk 1 (high),60622.0,2020-08-25,complaint,no entry,NaN,220 days,8,25
4,2386398,kiki's bistro,22899.0,restaurant,risk 1 (high),60610.0,2020-08-24,canvass,no entry,NaN,221 days,8,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...
215062,229233,"zullo's markets, llc",2016915.0,restaurant,risk 2 (medium),60661.0,2010-02-18,license,fail,NaN,4061 days,2,18
215063,68205,la fonda chiquita tlc,2017215.0,restaurant,risk 1 (high),60639.0,2010-02-09,license,fail,12. hand washing facilities: with soap and san...,4070 days,2,9
215064,88234,kabab cuisine 2,2014076.0,restaurant,risk 1 (high),60659.0,2010-02-01,license re-inspection,pass,NaN,4078 days,2,1
215065,74311,margarita distributors,2017298.0,wholesale,risk 3 (low),60608.0,2010-02-19,license re-inspection,pass,NaN,4060 days,2,19
215066,67838,our lady of lourdes,42577.0,daycare (under 2 years),risk 1 (high),60623.0,2010-01-12,canvass,fail,18. no evidence of rodent or insect outer open...,4098 days,1,12